sys_includedir = $(includedir)/system/
sys_include_HEADERS = system/sound_trigger.h \
            system/audio.h \
            system/audio_policy.h

audeffect_include_HEADERS = audio_effects/audio_effects_conf.h \
            audio_effects/effect_aec.h \
            audio_effects/effect_agc.h \
            audio_effects/effect_bassboost.h \
            audio_effects/effect_downmix.h \
            audio_effects/effect_environmentalreverb.h \
            audio_effects/effect_equalizer.h \
            audio_effects/effect_loudnessenhancer.h \
            audio_effects/effect_ns.h \
            audio_effects/effect_presetreverb.h \
            audio_effects/effect_virtualizer.h \
            audio_effects/effect_visualizer.h

audeffect_includedir = $(includedir)/audio_effects/

hardware_include_HEADERS = hardware/CryptoAPI.h \
              hardware/MetadataBufferType.h \
              hardware/HardwareAPI.h \
              hardware/HDCPAPI.h \
              hardware/OMXPluginBase.h \
              hardware/VideoAPI.h

hardware_includedir = $(includedir)/media/hardware/
