av/include/media/stagefright/MediaErrors.h     usr/include/media/stagefright/MediaErrors.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/ABase.h        usr/include/media/stagefright/foundation/ABase.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/AData.h        usr/include/media/stagefright/foundation/AData.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/ADebug.h       usr/include/media/stagefright/foundation/ADebug.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/AString.h      usr/include/media/stagefright/foundation/AString.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/Flagged.h      usr/include/media/stagefright/foundation/Flagged.h

av/media/libstagefright/foundation/include/media/stagefright/foundation/TypeTraits.h   usr/include/media/stagefright/foundation/TypeTraits.h
